on: [push, pull_request]
name: "Continuous Integration \U0001F44C\U0001F440"
jobs:
  perlCritic:
    name: Run Perl Critic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Perl Critic
      uses: Difegue/action-perlcritic@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: ./lib/* ./script/* ./tools/install.pl
  testSuite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Docker Build
      run: |
        docker pull difegue/lanraragi:nightly
        docker build --cache-from=difegue/lanraragi:nightly -t difegue/lanraragi -f ./tools/build/docker/Dockerfile .
    - name: LANraragi Test Suite
      uses: ./.github/action-run-tests
  testBrew:
    name: Test Homebrew version
    runs-on: macos-latest
    steps:
    - uses: actions/cache@v1
      with:
        path: ~/Library/Caches/Homebrew
        key: homebrew-cache-${{ hashFiles('**') }}
        restore-keys: |
          homebrew-cache-
    - uses: actions/checkout@master
    - name: Build and test bundled homebrew formula
      run: |
        tar -cvzf /tmp/lanraragi.tar.gz .
        cd tools/build/homebrew
        mv /tmp/lanraragi.tar.gz $(brew --cache -s Lanraragi.rb)
        brew update
        brew unlink node@12
        brew install --verbose --build-from-source Lanraragi.rb
        brew test --verbose Lanraragi.rb
        brew audit --verbose Lanraragi.rb
